var mongoose = require('mongoose');
var conn = mongoose.connect('mongodb://localhost/lol-synergy');
var Champion = require("../models/Champion");

//clears all database entries.
Champion.remove({}, function(err) {
  if (err) {
    console.log("ERROR:", err);
  }
});

 var champions = [
  {name: "Aatrox",       position: "top",     damage: "ad", softcc: 1, hardcc: 1,   tank: true,   engage: true,     seige:false,  waveclear:true,     aram: "1"},  
  {name: "Ahri",         position: "mid",     damage: "ap", softcc: 0, hardcc: 1,   tank: false,  engage: true,     seige:true,   waveclear:true,     aram: "3"},
  {name: "Akali",        position: "mid",     damage: "ap", softcc: 1, hardcc: 0,   tank: false,  engage: true,     seige:false,  waveclear:false,    aram: "1"},
  {name: "Alistar",      position: "support", damage: "ap", softcc: 0, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:false,    aram: "3"},
  {name: "Amumu",        position: "jungle",  damage: "ap", softcc: 1, hardcc: 1,   tank: true,   engage: true,     seige:true,   waveclear:false,    aram: "3"},
  {name: "Anivia",       position: "mid",     damage: "ap", softcc: 1, hardcc: 1,   tank: false,  engage: false,    seige:true,   waveclear:true,     aram: "3"},
  {name: "Annie",        position: "mid",     damage: "ap", softcc: 0, hardcc: 1,   tank: false,  engage: true,     seige:true,   waveclear:true,     aram: "3"},
  {name: "Ashe",         position: "adc",     damage: "ad", softcc: 1, hardcc: 1,   tank: false,  engage: true,     seige:true,   waveclear:true,     aram: "2"},
  {name: "Aurelion Sol", position: "mid",     damage: "ap", softcc: 0, hardcc: 1,   tank: false,  engage: true,     seige:false,  waveclear:true,     aram: "3"},
  {name: "Azir",         position: "mid",     damage: "ap", softcc: 0, hardcc: 1,   tank: false,  engage: true,     seige:true,   waveclear:true,     aram: "3"},
  {name: "Bard",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:false,    aram: "2"},
  {name: "Blitzcrank",   position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  {name: "Brand",        position: "mid",     damage: "ap", softcc: 0, hardcc: 1,   tank: false,  engage: false,    seige:false,  waveclear:true,     aram: "3"},
  {name: "Braum",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:false,    aram: "3"},
  {name: "Caitlyn",      position: "adc",     damage: "ad", softcc: 1, hardcc: 0,   tank: false,  engage: false,    seige:true,   waveclear:true,     aram: "3"},
  {name: "Cassiopeia",   position: "mid",     damage: "ap", softcc: 1, hardcc: 1,   tank: false,  engage: true,     seige:false,  waveclear:true,     aram: "3"},
  {name: "Cho'Gath",     position: "top",     damage: "ap", softcc: 2, hardcc: 1,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  {name: "Corki",        position: "mid",     damage: "ap", softcc: 0, hardcc: 0,   tank: false,  engage: false,    seige:true,   waveclear:true,     aram: "2"},
  {name: "Darius",       position: "top",     damage: "ad", softcc: 1, hardcc: 1,   tank: true,   engage: false,    seige:false,  waveclear:true,     aram: "2"},
  {name: "Diana",        position: "jungle",  damage: "ap", softcc: 0, hardcc: 1,   tank: false,  engage: true,     seige:true,   waveclear:true,     aram: "2"},
  {name: "Dr-Mundo",     position: "top",     damage: "ap", softcc: 1, hardcc: 0,   tank: true,   engage: false,    seige:true,   waveclear:false,    aram: "3"},
  {name: "Draven",       position: "adc",     damage: "ad", softcc: 1, hardcc: 0,   tank: false,  engage: false,    seige:true,   waveclear:true,     aram: "3"}
  // {name: "Ekko",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Elise",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Evelynn",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Ezreal",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Fiddlesticks", position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Fiora",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Fizz",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Galio",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Gangplank",    position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Garen",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Gnar",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Gragas",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Graves",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Hecarim",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Heimerdinger", position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Illaoi",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Irelia",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Janna",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Jarvan IV",    position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Jax",          position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Jayce",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Jhin",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Jinx",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kalista",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Karma",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Karthus",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kassadin",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Katarina",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kayle",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kennen",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kha'Zix",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kindred",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Kog'Maw",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "LeBlanc",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Lee Sin",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Leona",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Lissandra",    position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Lucian",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Lulu",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Lux",          position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Malphite",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Malzahar",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Maokai",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Master Yi",    position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Miss Fortune", position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Mordekaiser",  position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Morgana",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Nami",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Nasus",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Nautilus",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Nidalee",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Nocturne",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Nunu",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Olaf",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Orianna",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Pantheon",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Poppy",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Quinn",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Rammus",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Rek'Sai",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Renekton",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Rengar",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Riven",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Rumble",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Ryze",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Sejuani",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Shaco",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Shen",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Shyvana",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Singed",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Sion",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Sivir",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Skarner",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Sona",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Soraka",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Swain",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Syndra",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Tahm Kench",   position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Talon",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Taric",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Teemo",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Thresh",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Tristana",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Trundle",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Tryndamere",   position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Twisted Fate", position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Twitch",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Udyr",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Urgot",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Varus",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Vayne",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Veigar",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Vel'Koz",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Volibear",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Warwick",      position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Wukong",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"}, 
  // {name: "Xerath",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Xin Zhao",     position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Yasuo",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Yorick",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},  
  // {name: "Zac",          position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Zed",          position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Ziggs",        position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},           
  // {name: "Zilean",       position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"},
  // {name: "Zyra",         position: "support", damage: "ap", softcc: 1, hardcc: 2,   tank: true,   engage: true,     seige:true,   waveclear:true,     aram: "3"}
  ];


Champion.create(champions, function(err, docs) {
  if (err) {
    console.log("ERROR:", err);
  } else {
    console.log("Created:", docs);
    mongoose.connection.close();
  }
});